### ISSUE TITLE
Libraries(iostream) not Supported

### ISSUE THREAD

**Issue by SajinSabu** [dacap/pocketcpp#15]
path/program.CPP:1:21: fatal error: iostream.h: No such file or directory
 #include<iostream.h>

**Comment by iganinja** [comment]
Can you post the code, please?

**Comment by dacap** [comment]
I think you might have something like `#include <iostream.h>` while you should be using `#include <iostream>`

**Comment by raghav-kukreti** [comment]
It's probably `#include <iostream>` you should be using.
